### ISSUE TITLE
SCSS conflicts

### ISSUE THREAD

**Issue by rafaelfaria** [Nemo64/meteor-bootstrap#35] opened 2015-01-26 13:34 UTC
All my css files are written in scss, therefore i'm running the [fourseven:scss package](https://github.com/fourseven/meteor-scss) thing is that I think it conflicts, because it doesnt load bootstrap into the page.

I know so, because if i remove it, bootstrap is back on the page.

Any way to fix this?

Thanks

**Comment by emgee3** [comment] 2015-03-31 04:08
Hey @rafaelfaria I can't seem to reproduce this. If you provide a cloneable reproduction, I'll be happy to look into it.

**Comment by emgee3** [comment] 2015-04-26 20:27
Closing because no reproduction. Feel free to reopen with one.

**Closed by emgee3** 2015-04-26 20:27 UTC
